### ISSUE TITLE
Deadlock at startup

### ISSUE THREAD

**Issue by ankon** [Collaborne/tomcat-remoteip-aws-valve#4]
```
Found one Java-level deadlock:
=============================
"aws-ip-range-updater":
  waiting to lock monitor 0x00007fe9880062c8 (object 0x0000000733c57a58, a sun.net.www.protocol.file.Handler),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007fe9b0003828 (object 0x0000000733c3e038, a sun.net.www.protocol.jar.JarFileFactory),
  which is held by "aws-ip-range-updater"

Java stack information for the threads listed above:
===================================================
"aws-ip-range-updater":
    at sun.net.www.protocol.file.Handler.openConnection(Handler.java:72)
    - waiting to lock <0x0000000733c57a58> (a sun.net.www.protocol.file.Handler)
    at java.net.URL.openConnection(URL.java:979)
    at sun.net.www.protocol.jar.JarFileFactory.getConnection(JarFileFactory.java:65)
    at sun.net.www.protocol.jar.JarFileFactory.getPermission(JarFileFactory.java:154)
    at sun.net.www.protocol.jar.JarFileFactory.getCachedJarFile(JarFileFactory.java:126)
    at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:81)
    - locked <0x0000000733c3e038> (a sun.net.www.protocol.jar.JarFileFactory)
    at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
    at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
    at java.net.URL.openStream(URL.java:1045)
    at com.newrelic.weave.utils.ClassCache.getClassResource(ClassCache.java:66)
    at com.newrelic.weave.utils.ClassCache.getClassInformation(ClassCache.java:84)
    at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:192)
    at com.newrelic.weave.weavepackage.WeavePackageManager.weave(WeavePackageManager.java:243)
    at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.transform(ClassWeaverService.java:515)
    at com.newrelic.agent.instrumentation.context.InstrumentationContextManager$2.transform(InstrumentationContextManager.java:231)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:72)
    at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:405)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    - locked <0x000000072dabdc28> (a sun.net.www.protocol.https.HttpsClient)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at com.collaborne.operations.tomcat.AWSRemoteIpValve.updateIpRanges(AWSRemoteIpValve.java:159)
    at com.collaborne.operations.tomcat.AWSRemoteIpValve$2.run(AWSRemoteIpValve.java:69)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
"main":
    at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:81)
    - waiting to lock <0x0000000733c3e038> (a sun.net.www.protocol.jar.JarFileFactory)
    at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
    at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
    at java.net.URL.openStream(URL.java:1045)
    at com.newrelic.weave.utils.ClassCache.getClassResource(ClassCache.java:66)
    at com.newrelic.weave.utils.ClassCache.getClassInformation(ClassCache.java:84)
    at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:192)
    at com.newrelic.weave.weavepackage.WeavePackageManager.weave(WeavePackageManager.java:243)
    at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.transform(ClassWeaverService.java:515)
    at com.newrelic.agent.instrumentation.context.InstrumentationContextManager$2.transform(InstrumentationContextManager.java:231)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at java.net.URL.getURLStreamHandler(URL.java:1175)
    at java.net.URL.<init>(URL.java:420)
    at java.net.URL.<init>(URL.java:310)
    at java.net.URL.<init>(URL.java:333)
    at sun.net.www.protocol.file.Handler.openConnection(Handler.java:92)
    - locked <0x0000000733c57a58> (a sun.net.www.protocol.file.Handler)
    at sun.net.www.protocol.file.Handler.openConnection(Handler.java:72)
    - locked <0x0000000733c57a58> (a sun.net.www.protocol.file.Handler)
    at java.net.URL.openConnection(URL.java:979)
    at sun.net.www.protocol.jar.JarURLConnection.<init>(JarURLConnection.java:84)
    at sun.net.www.protocol.jar.Handler.openConnection(Handler.java:41)
    at java.net.URL.openConnection(URL.java:979)
    at org.apache.catalina.core.JreMemoryLeakPreventionListener.lifecycleEvent(JreMemoryLeakPreventionListener.java:385)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
    at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:401)
    - locked <0x00000007348378f8> (a org.apache.catalina.core.StandardServer)
    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:104)
    - locked <0x00000007348378f8> (a org.apache.catalina.core.StandardServer)
    at org.apache.catalina.startup.Catalina.load(Catalina.java:606)
    at org.apache.catalina.startup.Catalina.load(Catalina.java:629)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:311)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:494)

Found 1 deadlock.
```

This might be related to https://bugs.openjdk.java.net/browse/JDK-7146776 - deadlock between URLStreamHandler.getHostAddress and file.Handler.openconnection.

For now potential work-around/fix ideas:
1. Make sure we have a timeout on all the relevant parts
2. Delay the initial call (with the risk of requests not getting logged properly)

**Comment by ankon** [comment]
Note that this might also point to an issue with NewRelic doing class lookups while transforming classes.

**Comment by stnor** [comment]
I think this is related to NewRelic and is should be closed.

**Comment by ankon** [comment]
Ok, I think it's ok to close it now, and see whether it ever appears again. I haven't seen it back since then, so ... :)
